spring:
  datasource:
    url: jdbc:oracle:thin:@211.238.142.22:1521:xe
    username: hr
    password: happy
    driver-class-name: oracle.jdbc.driver.OracleDriver

  ai:
    google:
      genai:
        api-key: 
  jpa:
    database: oracle
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
        format_sql: true
        user_sql_comments: true
  thymeleaf:
    cache: false
    encoding: utf-8
    prefix: classpath:templates/
    suffix: .html
    mode: HTML

logging:
    level:
      org.hibernate.SQL: DEBUG
      org.hibernate.orm.jdbc.bind: TRACE
